name: Setup Oxenstored environment
description: Setup an Oxenstored environment for making opam calls.

runs:
  using: "composite"
  steps:
    - name: Update Ubuntu repositories
      shell: bash
      run: sudo apt-get update

    - name: Use disk with more space for TMPDIR and XDG_CACHE_HOME
      shell: bash
      run: |
        df -h || true
        export TMPDIR="/mnt/build/tmp"
        export XDG_CACHE_HOME="/mnt/build/cache"
        sudo mkdir -p "${TMPDIR}" "${XDG_CACHE_HOME}"
        sudo chown "$(id -u):$(id -g)" "${TMPDIR}" "${XDG_CACHE_HOME}"
        echo "TMPDIR=${TMPDIR}" >>"$GITHUB_ENV"
        echo "XDG_CACHE_HOME=${XDG_CACHE_HOME}" >>"$GITHUB_ENV"

    - name: Get runner OS info
      uses: kenchan0130/actions-system-info@master
      id: system-info

    # We set DUNE_CACHE_STORAGE_MODE, it is required for dune cache to work inside opam for now,
    # otherwise it gets EXDEV and considers it a cache miss
    - name: Use ocaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 4.14.2
        #opam-repositories: |
          #xs-opam: ${{ steps.dotenv.outputs.repository }}
        dune-cache: true
        opam-pin: true
        cache-prefix: v3-${{ steps.system-info.outputs.name }}-${{ steps.system-info.outputs.release }}
      env:
        DUNE_CACHE_STORAGE_MODE: copy

    - name: Install dependencies
      shell: bash
      run: opam install . --deps-only --with-test -v

    - name: list
      shell: bash
      run: opam list
