language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PACKAGE="xen-evtchn-unix"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - POST_INSTALL_HOOK="opam depext -ui mirage-xen"
   - PINS="xen-evtchn:."
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.07
   - DISTRO=ubuntu-lts OCAML_VERSION=4.06
   - DISTRO=ubuntu OCAML_VERSION=4.05
   - DISTRO=fedora OCAML_VERSION=4.04
   - DISTRO=alpine OCAML_VERSION=4.03
